services:
  postgres:
    image: bitnami/postgresql:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-dbagent}
    ports:
      - '5432:5432'
    volumes:
      - agent_postgres_data:/var/lib/postgresql/data
      - ./apps/dbagent/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ${POSTGRES_DB:-dbagent}']
      interval: 3s
      timeout: 1s
      retries: 5

  oceanbase-agent:
    image: davidzhangbj/oceanbaseagent:v0.1
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-dbagent}
      NODE_ENV: production
      PORT: 8000
    env_file: '.env.production'
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db_network

volumes:
  agent_postgres_data:

networks:
  db_network:
    driver: bridge
